### ISSUE TITLE
Support for multiple parent nodes?

### ISSUE THREAD

**Issue by Pangamma** [handihow/skilltreev2#4]
**Is your feature request related to a problem? Please describe.**
Depending on how the code is currently set up this may not be an easy change to make. It would be nice to be able to set multiple parent nodes for a child. In this way, you could require someone to unlock "jumping" as well as "running" before they would be able to unlock a "running jump". 

**Describe the solution you'd like**
- Allow picking more than one parent for a child node.
- Require all parents be unlocked before the child can be unlocked. (Or, require only one of them. Different people may have different preferences)

**Describe alternatives you've considered**
Manually writing that it requires other nodes as well before it can be unlocked.

**Additional context**

**Comment by handihow** [comment]
This is a feature requested as well on the underlying package Beautiful Skill Tree
https://github.com/andrico1234/beautiful-skill-tree/issues/56

Unfortunately, this package is abandoned, and I had to do some mumbo jumbo to be able to upgrade to React 18. 
So right now, the package is under my own code and I would be able to change it. But as you can see, after the discussions there is not a clear way forward to do this. 
My suggestion would be to create separate trees in the same view and then make it so that the student could not advance to the next tree without completing the first two trees. 

There is a way to disable the skilltree in the tree editor. So if you have a group of students, you can keep the skilltree locked (disabled) until they have reached that stage. It might be an idea to be able to "lock" or disable the skilltree per individual student.
